Update package-version.yaml

diff --git a/.github/workflows/package-version.yaml b/.github/workflows/package-version.yaml
--- a/.github/workflows/package-version.yaml
+++ b/.github/workflows/package-version.yaml
@@ -1,32 +1,187 @@
-name: 'Bump Version'
+name: CI
 
 on:
   push:
     branches:
-      - 'main'
+      - main
+  pull_request:
+    types: [assigned, opened, synchronize, reopened, labeled]
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
+  cancel-in-progress: true
+
+env:
+  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
+  NX_CLOUD_DISTRIBUTED_EXECUTION: true
+  NX_VERBOSE_LOGGING: false
 
 jobs:
-  bump-version:
-    name: 'Bump Version on master'
+  main:
+    name: Nx Cloud - Main Job
     runs-on: ubuntu-latest
-
+    env:
+      NX_CI_EXECUTION_ENV: "linux"
     steps:
-      - name: 'Checkout source code'
-        uses: 'actions/checkout@v2'
+      - uses: actions/checkout@v4
         with:
-          ref: ${{ github.ref }}
-      - name: 'cat package.json'
-        run: cat ./services/app/package.json
-      - name: 'Automated Version Bump'
-        id: version-bump
-        uses: 'phips28/gh-action-bump-version@master'
+          fetch-depth: 0
+
+      - uses: nrwl/nx-set-shas@v4
+
+      - name: Install primary node version (see volta config in package.json) and dependencies
+        uses: ./.github/actions/install-node-and-dependencies
+
+      - name: Run parallel distributed tasks
+        uses: jameshenry/parallel-bash-commands@v1
         with:
-          tag-prefix: 'v'
+          cmd1: npx nx-cloud record -- npx nx format:check
+          cmd2: npx nx run-many -t build --parallel=3
+          cmd3: npx nx run-many -t lint --parallel=3
+          cmd4: npx nx run-many -t test --parallel=3 --ci --maxWorkers=2
+          cmd5: npx nx run integration:integration --ci --maxWorkers=2
+
+      # e2e tests for everything except the primary task runner
+      - run: PUBLISHED_VERSION=999.9.9-e2e.0 npx nx run-many --t e2e --parallel=1
+
+      - name: Stop all running agents
+        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+        if: ${{ always() }}
+        run: npx nx-cloud stop-all-agents
+
+  agents:
+    name: Nx Cloud - Agent ${{ matrix.agent }}
+    runs-on: ubuntu-latest
+    env:
+      NX_CI_EXECUTION_ENV: "linux"
+    strategy:
+      matrix:
+        agent: [1, 2, 3, 4]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Configure git metadata
+        run: |
+          git config --global user.email test@example.com
+          git config --global user.name "Tester McPerson"
+
+      - name: Install primary node version (see volta config in package.json) and dependencies
+        uses: ./.github/actions/install-node-and-dependencies
+
+      - name: Start Nx Agent ${{ matrix.agent }}
+        run: npx nx-cloud start-agent
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: 'cat package.json'
-        run: cat ./services/app/package.json
-      - name: 'Output Step'
+          NX_AGENT_NAME: ${{ matrix.agent }}
+
+  windows-main:
+    name: Nx Cloud - Windows Main Job
+    runs-on: windows-latest
+    env:
+      NX_CI_EXECUTION_ENV: "windows"
+      LERNA_OS_TYPE: windows
+      # Set the temp directory to a short dir without username in it otherwise import command specs have a problem because of different paths on windows agents
+      TEMP: C:\temp
+      TMP: C:\temp
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install primary node version (see volta config in package.json) and dependencies
+        uses: ./.github/actions/install-node-and-dependencies
+
+      - name: Run parallel distributed unit and integration tests on windows
+        shell: bash
+        # From old maintainer regarding integration tests: "import is NOT TESTED in windows because pain and suffering"
+        run: |
+          pids=()
+          npx nx run integration:integration --ci --maxWorkers=2 &
+          pids+=($!)
+
+          # Ignored specs currently failing on windows
+          # TODO: investigate why
+          npx nx run-many -t test --parallel=3 --ci --maxWorkers=2 --testTimeout=60000 --testPathIgnorePatterns=save.spec.ts --testPathIgnorePatterns=find-file.spec.ts --testPathIgnorePatterns=chain-class.spec.ts &
+
+          pids+=($!)
+
+          for pid in "${pids[@]}"; do
+            wait "$pid"
+          done
+
+      - name: Stop all running agents for Nx Run Group
+        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+        if: ${{ always() }}
+        run: npx nx-cloud stop-all-agents
+
+  windows-agents:
+    name: Nx Cloud - Windows Agent ${{ matrix.agent }}
+    runs-on: windows-latest
+    strategy:
+      matrix:
+        agent: [1, 2, 3, 4]
+    env:
+      NX_CI_EXECUTION_ENV: "windows"
+      LERNA_OS_TYPE: windows
+      # Set the temp directory to a short dir without containing username, otherwise import command specs have a problem because of different paths on windows agents
+      TEMP: C:\temp
+      TMP: C:\temp
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Configure git metadata
+        run: |
+          git config --global user.email test@example.com
+          git config --global user.name "Tester McPerson"
+
+      - name: Install primary node version (see volta config in package.json) and dependencies
+        uses: ./.github/actions/install-node-and-dependencies
+
+      - name: Start Nx Agent ${{ matrix.agent }}
+        run: npx nx-cloud start-agent
         env:
-          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
-        run: echo "new tag $NEW_TAG"
+          NX_AGENT_NAME: ${{ matrix.agent }}
+
+  # Isolated e2e tests for the task runner which become too flaky if nested through further node child processes
+  task-runner-e2e:
+    name: Task Runner E2E
+    runs-on: ubuntu-latest
+    env:
+      # Silently disable nx cloud for task runner e2e (using NX_NO_CLOUD produces a warning log)
+      NX_CLOUD_ACCESS_TOKEN: ""
+      NX_CLOUD_DISTRIBUTED_EXECUTION: false
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Derive appropriate SHAs for base and head for `nx affected` commands
+        uses: nrwl/nx-set-shas@v4
+
+      - name: Configure git metadata
+        run: |
+          git config --global user.email test@example.com
+          git config --global user.name "Tester McPerson"
+
+      - name: Enable corepack
+        run: corepack enable
+        shell: bash
+
+      - name: Install dependencies
+        run: npm ci
+        shell: bash
+
+      - name: Check if e2e-run-task-runner is affected
+        id: check_affected
+        run: |
+          IS_AFFECTED_STR=$(npx nx print-affected | jq '.projects | contains(["e2e-run-task-runner"])')
+          IS_AFFECTED=$([[ $IS_AFFECTED_STR == 'true' ]] && echo 'true' || echo '')
+          echo "is_affected=$IS_AFFECTED" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - name: Prepare e2e tests for task-runner
+        if: ${{ steps.check_affected.outputs.is_affected }}
+        run: npx nx prepare-for-e2e e2e-run-task-runner
+        shell: bash
+
+      - name: Run e2e tests for task-runner
+        if: ${{ steps.check_affected.outputs.is_affected }}
+        run: e2e/run/task-runner/src/run-tests.sh
+        shell: bash
